spring:
  datasource:
    name: qmt  #????
    url: jdbc:mysql://localhost:3306/qmt?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC #url
    username: root  #???
    password: root  #??
    driver-class-name: com.mysql.cj.jdbc.Driver  #???????
  # redis????????????Redis????????pom???????????API????
  redis:
    # Redis?????????0?
    database: 1
    # Redis?????
    host: 127.0.0.1
    # Redis???????
    port: 6379
    # Redis?????????????
    # password:
    # ??????
    timeout: 10s
    lettuce:
      pool:
        # ????????
        max-active: 200
        # ???????????????????????
        max-wait: -1ms
        # ???????????
        max-idle: 10
        # ???????????
        min-idle: 0
server:
  port: 8085

# Mybatis-Plus ?????
mybatis-plus:
  # ???????---?????
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # ??mapper?????????mapper.xml????---???????????mapper?????@Mapper??????????
  type-aliases-package: com.qmt.qmtadvertserverclient.entity
  # ??????????
  config-location: classpath:mybatis-config.xml

# Sa-Token??
sa-token:
  # token?? (????cookie??)
  token-name: qmt
  # token??
  # token-prefix: ZSAndroid
  # token??????s ??30?, -1??????
  timeout: 2592000
  # token????? (???????????token??) ??: ?
  activity-timeout: -1
  # ???????????? (?true???????, ?false?????????)
  is-concurrent: false
  # ?????????????????token (?true?????????token, ?false?????????token)
  is-share: false
  # token??
  token-style: random-64 # ??64????
  # ????????
  is-log: false
  # ????? cookie ??? Token ???? true
  isReadCookie: true
  # ????? header ??? Token???? true
  isReadHead: true
  # ????? ??? ??? Token???? true
  isReadBody: true
  # ?? Token-Session ??????? (?????true??????? Token-Session ???????) ??? true
  tokenSessionCheckLogin: true
  ## aliyun oss
  ## 配置说明参考: com.ljq.demo.springboot.common.config.OSSConfig.class
